mqtt.host: 192.168.99.100
mqtt.port: 31883
nao.url: tcp://192.168.0.3:9559
server.port: 9050
---
spring:
    profiles: production
mqtt:
  host: ${mqtt_host}
  port: ${mqtt_port}
nao:
  url: ${nao_url}
server:
  port: 9050